# This is a basic workflow to help you get started with Actions

name: Test CI/CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        
    # Runs a set of commands using the runners shell
    - name: Generate commit log
      run: |     
       git log --pretty=format:"GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S') %n%nLatest Commit %H%n%n    %s%n%n    %b" --date=short -n 1 > commit_msg.log
       cat commit_msg.log
       
    - name: Create release APK name
      run: |
        export APK_NAME="release_$(date +'%Y-%m-%d')"
        echo "::set-env name=NEW_APK_NAME::$APK_NAME"
      
    # Test Env Variable
    - name: Test Env Variable
      env:
        key_1: ${{ secrets.KEY_1 }}
        key_2: "Hi~"
        # https://github.com/actions/starter-workflows/issues/68#issuecomment-524665878
        commit_msg: $(cat commit_msg.log)
      run: |
        echo "Env key_1: ${key_1}"
        echo "Env key_2: ${key_2}"
        echo "Secrets key_1: ${{ secrets.KEY_1 }}"
        echo "Env commit_msg: ${commit_msg}"
        echo "::set-env name=COMMIT_MSG::$(cat commit_msg.log)"
        echo "Env COMMIT_MSG: ${{ env.COMMIT_MSG }}"
        echo "Env NEW_APK_NAME: ${{ env.NEW_APK_NAME }}"
        
    - name: Test Action Parameter 
      uses: wxdlong/hello-action@v7
      with:
        who-to-greet: 'Mona the Octocat %n Hi /n HELLO $(cat commit_msg.log) /n ${{ env.COMMIT_MSG }} /n ${{ env.NEW_APK_NAME }}'
